version: "3"

services:
    php:
        build:
            context: ./
            target: php
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        volumes:
            - ./app:/srv:rw,cached
            - ./docker/php/conf.d/dev.ini/:/usr/local/etc/php/conf.d/php.ini

    nginx:
        build:
            context: ./
            target: nginx
        depends_on:
            - php
        volumes:
            - ./app/public:/srv/public:ro
        ports:
            - target: 80
              published: 3000
              protocol: tcp

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - TZ=${POSTGRES_TZ}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - target: 5432
              published: 5432
              protocol: tcp

volumes:
    db-data: {}
