doctrine:
    dbal:
        host: '%env(resolve:POSTGRES_SERVICE)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        server_version: '%env(resolve:POSTGRES_VERSION)%'
        driver: '%env(resolve:POSTGRES_DRIVER)%'
        charset: '%env(resolve:POSTGRES_CHARSET)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
